= проблема дедупликации сообщений.

Подумать, как бороться с проблемой дедупликации сообщений. +
о чем речь. При плохом интернете может произойти следующая ситуация.
Клиентом отправлен POST запрос, сервер его получил. Отправил ответ success.
Но ответ клиентом не был получен. Сервер применил изменения из POST.
А клиент будет повторно слать те же самые данные.
Поэтому надо сделать так, чтобы данные были уникальны.
При повторном их применении ничего не происходит. +
Решение: на уровень данных выносятся поля tds->tdc->tuc->tus + change time - это должно быть уникальным ключом, который избавит от проблемы дедупликации сообщений
берем например tds+changetime для каждого поля это с высокой вероятнстью уникальное значение - но это для каждого поля.
(возможно будет достаточным использовать tds+tuc - время когда сервер отдал данные + время когда клиент запросил отправку данных.
тогда это будет впринципе проверять всю эту сущность как одну транзакцию) - нет так нельзя, есть сложности с записью поля tuc - надо проверять каждое поле
