== Получение данных

Пользователь получает данные через `GET /data/{id}`



[source, json]
----
{
  "mcv":2,
  "tds":1501688742045,
  "ui":[
    {
      "t":1501688742045,
      "rev":33,
      "name":""
    }
  ],
  "tc":1501688742045,
  "tu":1501688742045,
  "data":{
    "title":[
      {
        "t":1501688742045,
        "v":"Title for entity"
      }
    ],
    "body":[
      {
        "t":1501688742045,
        "v":"Can be long <h2>html</h2> text"
      }
    ],
    "objectref":[
      {
        "t":1501688742045,
        "v":{
          "id":4,
          "name":"IMG_20150324_120506.jpg"
        }
      }
    ],
    "location":[
      {
        "t":1501688742045,
        "v":{
          "lon":49.1420645,
          "lat":55.7745272,
          "date":1422336455000
        }
      }
    ],
    "photos":{
      "photoUniqueIdentificator1":[
        {
          "t":1501688742045,
          "v":{
            "name":"image1",
            "ref":"ubrewergwERGWHhwe4y54gGEg45gQwef"
          }
        }
      ]
    }
  }
}
----
[cols="1,2", options="header"]
|===
|Field
|Info

|mcv
|link:../versioning/versioning.adoc[о версионировании] +
link:../migration/migration.adoc[о миграции]

|===

Но чтобы отправить свои изменения от делает `POST /changes/{id}`. не `/data/{id}` - этого роута вообще быть не должно и не будет

[source, json]
----
{
  "mcv":2,
  "tds":1458965214,
  "tdc":1456874526,
  "tuc":1456889564,
  "failedUploads":[
    {
      "time":14568745445,
      "cause":"Тут текст или код ошибки надо отправлять. ошибка может быть локальная или от сервера."
    }
  ],
  "changes":{
    "title":[
      {
        "t":1456987562,
        "v":"Первое изменение поля"
      },
      {
        "t":1456987662,
        "v":null
      }
    ],
    "photos.uniqueIdentif1":[
      {
        "t":153456789112,
        "v":"any object structure that confirm to protocol"
      },
      {
        "t":153456789112,
        "v":null
      }
    ]
  }
}
----

[cols="1,4"]
|===
|mcv
|Это именно то поле, которое пришло с задачей. Передаем его в неизменном виде. Это нужно для миграции. link:../migration/migration.adoc[о миграции]

| td* и tu*
| Детальное описание предназначения полей начинающихся на td* и tu* тут - link:../migration/migration.adoc[о переменных времени]

|tds
|Это то поле которое мы получаем от сервера, используем его в неизменном виде, просто отсылаем обратно.
В паре с полями описанными ниже все это используется для журналирования и решения некоторых технических проблем +
link:../journaling/problems.adoc[подробнее]

|tdc
|Когда клиент получил данные от сервера он должен был записать сюда свое локальное время.
Просто используем это значение и передаем в неизменном виде.

|tuc
|Это локальное время постановки этого перечня изменений на отправку. Это спорное поле. Тут надо будет подумать как это реализовывать. Пока на это поле стараемся ничего не завязывать. см проблемы дедупликации выше. Тесно связано с failedUploads

|failedUploads
|Опциональное поле. Каждый раз когда пользователь в ручном режиме жмет кнопку отправить изменения на сервер(принудительно синхронизирует) и это не выполняется из-за разного рода ошибок - это время журналируется
|===


